imports:
    - { resource: parameters.yml }

doctrine:
    mapping:   %config_dir%
    cache_dir: %cache_dir%/doctrine/
    config:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

csrf:
    secret: %csrf_secret%
